package flagmtx

var (
    FLAG_MTX = [][]string{
        {"b.", "b:", "b~", "b!", "b7", "b?", "bJ", "bY", "bY", "bY", "bY", "bY", "bY", "bJ", "bJ", "b?", "b7", "b!", "b~", "b^", "b:", "b:", "b.", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b ", "b "},
        {"bY", "bP", "bG", "bG", "bG", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bG", "bG", "bP", "b5", "bY", "bJ", "b?", "b7", "b!", "b~", "b^", "b:", "b:", "b:", "b.", "b.", "b.", "b.", "b:", "b:", "b:", "b^", "b~", "b7", "bJ", "bJ", "b."},
        {"bJ", "bG", "bG", "bG", "bG", "bG", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bG", "bG", "bG", "bP", "bP", "bP", "bP", "bP", "bP", "bP", "bP", "bP", "bG", "bG", "bG", "bG", "b~"},
        {"b!", "bG", "bG", "bG", "bG", "bG", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bP", "bP", "bP", "bP", "bG", "bG", "bG", "b7"},
        {"b^", "bP", "bG", "bG", "bG", "bG", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bP", "bP", "bP", "bP", "bP", "bG", "bG", "bG", "bY"},
        {"b:", "bP", "bG", "bG", "bG", "bG", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bP", "bP", "bP", "bP", "bP", "bP", "bG", "bG", "b5"},
        {"b.", "b5", "bG", "bG", "bG", "bG", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bP", "bP", "bP", "bP", "bP", "bP", "bG", "bG", "bP"},
        {"b.", "b5", "bG", "bP", "bP", "bP", "bP", "bP", "b5", "bP", "bP", "bP", "bP", "bP", "bP", "bP", "bG", "bG", "bG", "bG", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bB", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bP", "bP", "bP", "bP", "bP", "bG", "bG", "bG", "bG"},
        {"y ", "y!", "y7", "y7", "y7", "y7", "y7", "y?", "y?", "y?", "y?", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "bY", "bY", "bY", "b5", "b5", "b5", "bP", "bP", "bP", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bG", "bP", "bP", "bP", "bP", "y5", "y5", "yY", "yJ"},
        {"y ", "y^", "y~", "y!", "y!", "y7", "y7", "y?", "y?", "y?", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "y?", "y?", "y?", "y?", "y7", "y7", "y7", "y7", "y7", "y7", "y7", "y7", "y7", "y7", "y7", "y7", "y!", "y!", "y!", "y~", "y~", "y~", "y~", "y~"},
        {"y ", "y^", "y~", "y!", "y!", "y7", "y7", "y?", "y?", "y?", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "y?", "y?", "y?", "y?", "y7", "y7", "y7", "y!", "y!", "y!", "y~", "y~", "y~", "y~", "y~", "y^", "y^", "y^", "y^", "y~", "y~", "y~", "y~"},
        {"y.", "y~", "y~", "y!", "y!", "y7", "y7", "y?", "y?", "y?", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "y?", "y?", "y?", "y?", "y7", "y7", "y7", "y!", "y!", "y!", "y!", "y~", "y~", "y~", "y~", "y~", "y~", "y^", "y~", "y~", "y~", "y~", "y~"},
        {"y.", "y~", "y~", "y!", "y!", "y7", "y7", "y?", "y?", "y?", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "y?", "y?", "y?", "y?", "y7", "y7", "y7", "y!", "y!", "y!", "y!", "y~", "y~", "y~", "y~", "y~", "y~", "y^", "y~", "y~", "y~", "y~", "y^"},
        {"y:", "y~", "y~", "y!", "y!", "y7", "y7", "y?", "y?", "y?", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "y?", "y?", "y?", "y?", "y7", "y7", "y7", "y!", "y!", "y!", "y!", "y~", "y~", "y~", "y~", "y~", "y~", "y^", "y~", "y~", "y~", "y~", "y:"},
        {"y^", "y~", "y~", "y!", "y!", "y7", "y7", "y7", "y7", "y7", "y7", "y?", "y?", "y?", "y?", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "yJ", "y?", "y?", "y?", "y7", "y7", "y7", "y!", "y!", "y!", "y!", "y~", "y~", "y~", "y~", "y~", "y~", "y^", "y~", "y~", "y~", "y~", "y."},
        {"y:", "y:", "y.", "y.", "y.", "y.", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y.", "y.", "y.", "y:", "y:", "y^", "y^", "y~", "y!", "y7", "y7", "y7", "y?", "y?", "y?", "y7", "y7", "y7", "y7", "y!", "y!", "y!", "y!", "y~", "y~", "y~", "y~", "y~", "y^", "y~", "y~", "y~", "y^", "y "},
        {"y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y ", "y.", "y.", "y.", "y:", "y:", "y:", "y:", "y^", "y^", "y^", "y:", "y:", "y:", "y:", "y:", "y.", "y.", "y.", "y.", "y ", "y ", "y "},  
    }
)